"""
Byte-for-byte validation against the official HQC-1 KAT vectors.

KAT = Known Answer Test: the NIST submission ships a file of fixed (seed -> pk,
sk, ct, ss) tuples produced by the reference C implementation. Reproducing every
byte of those tuples is the strongest correctness check available, it proves
this Python port is bit-compatible with the reference, not merely self-consistent.
This is why the KAT tests use the deterministic *_det entry points (keygen and
encaps seeded explicitly) rather than the randomised public API: the randomness
must come from the vector seed, not from the OS.

The file PQCkemKAT_2321.rsp was generated by the reference implementation
using the SHAKE256 DRBG from the HQC 2025 KAT framework. To reproduce it,
the same DRBG is initialised with the vector seed and bytes are drawn in
the same order as the reference:
  32 bytes -> seed_kem  (for keygen)
  16 bytes -> m         (for encaps)
  16 bytes -> salt      (for encaps)

KAT_N caps how many of the vectors are checked (default 10); raise it for a more
exhaustive run, e.g. `KAT_N=100 pytest tests/test_kat.py`.
"""

import os
import pytest
from hqc.params import HQC1
from hqc.kem import kem_decaps, _kem_keygen_det, _kem_encaps_det
from hqc.drbg import NIST_DRBG

KAT_FILE = os.path.join(os.path.dirname(__file__), '..', 'kat', 'PQCkemKAT_2321.rsp')

# Number of vectors to test. Override with: KAT_N=5 pytest ...
_KAT_N = int(os.environ.get('KAT_N', '100'))


def parse_kat(filepath: str) -> list[dict]:
    """Read the NIST .rsp test-vector file into a list of dictionaries.

    The file is plain text: `key = value` lines grouped into blocks, one block
    per test vector, with a blank line between blocks. Each block has 6 fields:

        count = 0          <- vector number (decimal)
        seed = 061550...   <- 48-byte DRBG seed (hex)
        pk = 64AB...        <- expected public key  (hex)
        sk = 64AB...        <- expected secret key  (hex)
        ct = 1F2E...        <- expected ciphertext  (hex)
        ss = 9C0D...        <- expected shared secret (hex)

    This function turns each block into a dict like
        {'count': 0, 'seed': b'...', 'pk': b'...', ...}
    and returns the list of all such dicts. `count` is kept as an int; every
    other field is hex text and is decoded into raw bytes ready to compare
    against what the implementation produces."""
    vectors = []          # one dict per parsed block
    current = {}          # the block currently being read
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):    # skip blank lines and the header comment
                continue
            if '=' in line:                         # data lines look like "key = value"
                key, val = line.split('=', 1)       # split on the first '=' only
                key = key.strip()
                val = val.strip()
                if key == 'count':                  # count is decimal; every other field is hex
                    current[key] = int(val)
                else:
                    current[key] = bytes.fromhex(val)
            # a block ends at 'ss'; with all 6 keys present the vector is complete
            if 'ss' in current and len(current) >= 6:
                vectors.append(current)
                current = {}
    return vectors


@pytest.mark.skipif(not os.path.exists(KAT_FILE), reason="KAT file not found")
@pytest.mark.parametrize("idx", range(_KAT_N))
def test_kat_hqc1_keygen(idx):
    """pk and sk match the KAT vector."""
    vectors = parse_kat(KAT_FILE)
    v = vectors[idx]

    # Rebuild the exact randomness the reference used: seed the DRBG with the
    # vector's seed and draw seed_kem first, matching the reference byte order.
    drbg = NIST_DRBG(v['seed'])
    seed_kem = drbg.randombytes(HQC1.seed_bytes)

    ek, dk = _kem_keygen_det(seed_kem, HQC1)

    assert ek == v['pk'], f"KAT[{idx}]: pk mismatch"   # ek is the encapsulation key (public key)
    assert dk == v['sk'], f"KAT[{idx}]: sk mismatch"   # dk is the decapsulation key (secret key)


@pytest.mark.skipif(not os.path.exists(KAT_FILE), reason="KAT file not found")
@pytest.mark.parametrize("idx", range(_KAT_N))
def test_kat_hqc1_encaps(idx):
    """ct and ss match the KAT vector."""
    vectors = parse_kat(KAT_FILE)
    v = vectors[idx]

    # Draw the three values in the reference's fixed order: seed_kem, then the
    # message m, then the salt. The order matters -- the DRBG is a single stream.
    drbg = NIST_DRBG(v['seed'])
    seed_kem = drbg.randombytes(HQC1.seed_bytes)
    m        = drbg.randombytes(HQC1.k // 8)
    salt     = drbg.randombytes(HQC1.salt_bytes)

    ek, _dk = _kem_keygen_det(seed_kem, HQC1)   # regenerate the same key pair as keygen
    K, ct   = _kem_encaps_det(ek, m, salt, HQC1)

    assert ct == v['ct'], f"KAT[{idx}]: ct mismatch"   # ciphertext
    assert K  == v['ss'], f"KAT[{idx}]: ss mismatch"   # shared secret


@pytest.mark.skipif(not os.path.exists(KAT_FILE), reason="KAT file not found")
@pytest.mark.parametrize("idx", range(_KAT_N))
def test_kat_hqc1_decaps(idx):
    """decaps on the KAT ciphertext produces the correct ss."""
    vectors = parse_kat(KAT_FILE)
    v = vectors[idx]

    # Feed the vector's own sk and ct straight into decaps (no DRBG needed here)
    # and check it recovers the published shared secret -- the receiver side.
    K = kem_decaps(v['sk'], v['ct'], HQC1)
    assert K == v['ss'], f"KAT[{idx}]: decaps ss mismatch"
