"""
Byte-for-byte validation against the official HQC-1 KAT vectors.

The file PQCkemKAT_2321.rsp was generated by the reference implementation
using the SHAKE256 DRBG from the HQC 2025 KAT framework. To reproduce it,
the same DRBG is initialised with the vector seed and bytes are drawn in
the same order as the reference:
  32 bytes -> seed_kem  (for keygen)
  16 bytes -> m         (for encaps)
  16 bytes -> salt      (for encaps)
"""

import os
import pytest
from hqc.params import HQC1
from hqc.kem import kem_decaps, _kem_keygen_det, _kem_encaps_det
from hqc.drbg import NIST_DRBG

KAT_FILE = os.path.join(os.path.dirname(__file__), '..', 'kat', 'PQCkemKAT_2321.rsp')

# Number of vectors to test. Override with: KAT_N=5 pytest ...
_KAT_N = int(os.environ.get('KAT_N', '10'))


def parse_kat(filepath: str) -> list[dict]:
    """Parse the NIST count/seed/pk/sk/ct/ss response format."""
    vectors = []
    current = {}
    with open(filepath) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            if '=' in line:
                key, val = line.split('=', 1)
                key = key.strip()
                val = val.strip()
                if key == 'count':
                    current[key] = int(val)
                else:
                    current[key] = bytes.fromhex(val)
            if 'ss' in current and len(current) >= 6:
                vectors.append(current)
                current = {}
    return vectors


@pytest.mark.skipif(not os.path.exists(KAT_FILE), reason="KAT file not found")
@pytest.mark.parametrize("idx", range(_KAT_N))
def test_kat_hqc1_keygen(idx):
    """pk and sk match the KAT vector."""
    vectors = parse_kat(KAT_FILE)
    v = vectors[idx]

    drbg = NIST_DRBG(v['seed'])
    seed_kem = drbg.randombytes(HQC1.seed_bytes)

    ek, dk = _kem_keygen_det(seed_kem, HQC1)

    assert ek == v['pk'], f"KAT[{idx}]: pk mismatch"
    assert dk == v['sk'], f"KAT[{idx}]: sk mismatch"


@pytest.mark.skipif(not os.path.exists(KAT_FILE), reason="KAT file not found")
@pytest.mark.parametrize("idx", range(_KAT_N))
def test_kat_hqc1_encaps(idx):
    """ct and ss match the KAT vector."""
    vectors = parse_kat(KAT_FILE)
    v = vectors[idx]

    drbg = NIST_DRBG(v['seed'])
    seed_kem = drbg.randombytes(HQC1.seed_bytes)
    m        = drbg.randombytes(HQC1.k // 8)
    salt     = drbg.randombytes(HQC1.salt_bytes)

    ek, _dk = _kem_keygen_det(seed_kem, HQC1)
    K, ct   = _kem_encaps_det(ek, m, salt, HQC1)

    assert ct == v['ct'], f"KAT[{idx}]: ct mismatch"
    assert K  == v['ss'], f"KAT[{idx}]: ss mismatch"


@pytest.mark.skipif(not os.path.exists(KAT_FILE), reason="KAT file not found")
@pytest.mark.parametrize("idx", range(_KAT_N))
def test_kat_hqc1_decaps(idx):
    """decaps on the KAT ciphertext produces the correct ss."""
    vectors = parse_kat(KAT_FILE)
    v = vectors[idx]

    K = kem_decaps(v['sk'], v['ct'], HQC1)
    assert K == v['ss'], f"KAT[{idx}]: decaps ss mismatch"
